In [3]:
import numpy as np


In [11]:
m1 = np.array([10,20,30,40],float)
m1

array([10., 20., 30., 40.])

In [12]:
m1.dtype

dtype('float64')

In [13]:
m1.astype(str)

array(['10.0', '20.0', '30.0', '40.0'], dtype='<U32')

In [25]:
m = np.identity(3) 
m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
x = np.arange(10,20)


In [18]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
x.size

10

In [21]:
x.ndim

1

In [26]:
m.ndim

2

In [27]:
x.size,x.ndim

(10, 1)

In [30]:
x.reshape(5,2)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [31]:
x.resize(2,5)

In [32]:
x

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
x.ravel()

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [42]:
x = np.append(x,[23,45,67])

In [43]:
x = np.append(x,(3490,11))

In [44]:
x

array([  10,   11,   12,   13,   14,   15,   16,   17,   18,   19,   23,
         45,   67, 3490,   11])

In [46]:
x.reshape(5,3)

array([[  10,   11,   12],
       [  13,   14,   15],
       [  16,   17,   18],
       [  19,   23,   45],
       [  67, 3490,   11]])

In [47]:
x.resize(5,3)

In [48]:
x

array([[  10,   11,   12],
       [  13,   14,   15],
       [  16,   17,   18],
       [  19,   23,   45],
       [  67, 3490,   11]])

In [51]:
np.delete(x,1,axis=0)

array([[  10,   11,   12],
       [  16,   17,   18],
       [  19,   23,   45],
       [  67, 3490,   11]])

In [66]:
 #Multiply
a  = np.multiply(x,10)
print(a)

[[  100   110   120]
 [  130   140   150]
 [  160   170   180]
 [  190   230   450]
 [  670 34900   110]]


In [67]:
 #Divide
a = np.divide(a,10)
a = a.astype(int)
print(a.dtype)
print(a)

int32
[[  10   11   12]
 [  13   14   15]
 [  16   17   18]
 [  19   23   45]
 [  67 3490   11]]


In [70]:
print(np.floor_divide(a,10))

[[  1   1   1]
 [  1   1   1]
 [  1   1   1]
 [  1   2   4]
 [  6 349   1]]


In [73]:
print(np.power(a,2))

[[     100      121      144]
 [     169      196      225]
 [     256      289      324]
 [     361      529     2025]
 [    4489 12180100      121]]


In [74]:
print(np.mod(a,10))

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [9 3 5]
 [7 0 1]]


In [75]:
np.cumsum(a)

array([  10,   21,   33,   46,   60,   75,   91,  108,  126,  145,  168,
        213,  280, 3770, 3781], dtype=int32)

In [76]:
np.cumprod(a)

array([         10,         110,        1320,       17160,      240240,
           3603600,    57657600,   980179200,   463356416,   213837312,
         623290880, -2016681472, -1973672448,  1010699264, -1767209984],
      dtype=int32)

In [78]:
"""
 [  10   11   12]
 [  13   14   15]
 [  16   17   18]
 [  19   23   45]
 [  67 3490   11]
 """
np.sum(a,axis=1)

array([  33,   42,   51,   87, 3568])

In [79]:
np.sum(a,axis=0)

array([ 125, 3555,  101])

In [80]:
np.mean(a)

252.06666666666666

In [81]:
np.mean(a,axis=0)

array([ 25. , 711. ,  20.2])

In [82]:
np.mean(a,axis=1)

array([  11.        ,   14.        ,   17.        ,   29.        ,
       1189.33333333])

In [83]:
np.std(a,axis=1)

array([8.16496581e-01, 8.16496581e-01, 8.16496581e-01, 1.14309521e+01,
       1.62697763e+03])

In [84]:
np.min(a,axis=1)

array([10, 13, 16, 19, 11])

In [85]:
np.max(a,axis=1)

array([  12,   15,   18,   45, 3490])

In [89]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [118]:
n = np.full((4,4),True)

In [119]:
n

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [124]:
m = np.full((4,4),False)
m

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [121]:
#create 4x4 array whose diagonal element should be True and Non diagonal False
for i in range(4):
    for j in range(4):
        if i==j:
            m[i][j]=True
        

In [122]:
m

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [123]:
#create 4x4 array whose diagonal element should be False and Non diagonal True
for i in range(4):
    for j in range(4):
        if i==j:
            n[i][j]=False
print(n)    

[[False  True  True  True]
 [ True False  True  True]
 [ True  True False  True]
 [ True  True  True False]]
